# Generated by Django 2.2.15 on 2020-08-20 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodo', '0002_auto_20200820_1613'),
        ('insumo', '0004_insumo_stock'),
        ('apps', '0007_auto_20200819_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asig_insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asig', models.DateField(default=datetime.datetime.now)),
                ('cantero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.Cantero')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodo.Periodo')),
            ],
            options={
                'verbose_name': 'asig_insumo',
                'db_table': 'asig_insumo',
                'verbose_name_plural': 'asig_insumo',
            },
        ),
        migrations.CreateModel(
            name='Detalle_asig_insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('asig_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignar_insumo.Asig_insumo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.Insumo')),
            ],
            options={
                'verbose_name': 'detalle_asig_insumo',
                'db_table': 'detalle_asig_insumo',
                'verbose_name_plural': 'detalles_asig_insumos',
            },
        ),
    ]
