# Generated by Django 2.2.15 on 2020-09-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dimesion', models.IntegerField(choices=[(1, 'METROS'), (0, 'HECTAREAS')], default=1)),
                ('valor_dim', models.FloatField(max_length=13)),
                ('estado', models.IntegerField(choices=[(0, 'ACTIVO'), (1, 'INACTIVO')], default=1)),
            ],
            options={
                'db_table': 'cantero',
                'ordering': ['-nombre', '-valor_dim'],
                'verbose_name_plural': 'canteros',
                'verbose_name': 'cantero',
            },
        ),
    ]
