# Generated by Django 2.2.15 on 2020-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('genero', models.IntegerField(choices=[(1, 'MASCULINO'), (0, 'FEMENINO')], default=1)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.IntegerField(choices=[(1, 'INACTIVO'), (0, 'ACTIVO')], default=1)),
            ],
            options={
                'verbose_name': 'trabajador',
                'verbose_name_plural': 'trabajadores',
                'ordering': ['-nombres', '-cedula'],
                'db_table': 'trabajador',
            },
        ),
    ]
