# Generated by Django 2.2.15 on 2020-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'labor',
                'verbose_name_plural': 'labores',
                'ordering': ['id', 'nombre'],
                'db_table': 'labor',
            },
        ),
    ]
