# Generated by Django 2.2.15 on 2020-08-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='valor_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
