# Generated by Django 2.2.15 on 2020-09-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='user',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
    ]
