# Generated by Django 2.2.15 on 2020-09-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200917_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user/admin.png', null=True, upload_to='user/%Y/%m/%d'),
        ),
    ]
