# Generated by Django 2.2.15 on 2020-08-29 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('periodo', '0001_initial'),
        ('cantero', '0001_initial'),
        ('presentacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('cantidad', models.IntegerField(default=0)),
                ('cantero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantero.Cantero')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodo.Periodo')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presentacion.Presentacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
            options={
                'verbose_name_plural': 'producciones',
                'verbose_name': 'produccion',
                'db_table': 'produccion',
            },
        ),
    ]
