# Generated by Django 2.2.15 on 2020-08-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='presentacion',
        ),
    ]
