# Generated by Django 2.2.15 on 2020-08-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_remove_produccion_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='cantero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cantero.Cantero'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.Producto'),
        ),
    ]
