# Generated by Django 2.2.15 on 2020-09-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_auto_20200830_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='perdida',
            field=models.IntegerField(default=0),
        ),
    ]
