# Generated by Django 2.2.15 on 2020-09-14 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignar_labor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asignar_labor.Asig_labor')),
            ],
            options={
                'db_table': 'historial_pago',
                'verbose_name_plural': 'historial_pagos',
                'verbose_name': 'historial_pago',
            },
        ),
    ]
