# Generated by Django 2.2.15 on 2020-08-27 18:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignar_labor', '0003_auto_20200826_1353'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asignar_labor.Asig_labor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'historial_pagos',
                'verbose_name': 'historial_pago',
                'db_table': 'historial_pago',
            },
        ),
    ]
