# Generated by Django 2.2.15 on 2020-08-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Tipo_doc',
            new_name='tipo_doc',
        ),
    ]
