# Generated by Django 2.2.15 on 2020-08-12 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('presentacion', '0001_initial'),
        ('insumo', '0002_auto_20200812_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.IntegerField(choices=[(0, 'ACTIVO'), (1, 'INACTIVO')], default=1)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedor.Proveedor')),
            ],
            options={
                'ordering': ['id', 'proveedor'],
                'verbose_name_plural': 'compras',
                'verbose_name': 'compra',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.Compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.Insumo')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presentacion.Presentacion')),
            ],
            options={
                'ordering': ['id', 'compra'],
                'verbose_name_plural': 'detalles_compras',
                'verbose_name': 'detalle_compra',
                'db_table': 'detalle_compra',
            },
        ),
    ]
