# Generated by Django 2.2.15 on 2020-08-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.Compra'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumo.Insumo'),
        ),
    ]
