# Generated by Django 2.2.15 on 2020-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.IntegerField(choices=[(0, 'FINALIZADA'), (1, 'PENDIENTE')], default=1),
        ),
    ]
