# Generated by Django 2.2.15 on 2020-08-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_auto_20200815_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.Compra'),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.Insumo'),
        ),
    ]
