# Generated by Django 2.2.15 on 2020-08-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20200819_1250'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(choices=[(0, 'FINALIZADA'), (1, 'PENDIENTE')], default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Venta')),
            ],
            options={
                'verbose_name': 'detalle_venta',
                'db_table': 'detalle_venta',
                'verbose_name_plural': 'detalles_ventas',
            },
        ),
    ]
