# Generated by Django 2.2.15 on 2020-09-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20200830_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(choices=[(0, 'DEVUELTA'), (1, 'FINALIZADA')], default=1),
        ),
    ]
