# Generated by Django 2.2.15 on 2020-09-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20200910_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='pvp_moment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
