# Generated by Django 2.2.15 on 2020-09-14 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodo', '0001_initial'),
        ('trabajador', '0001_initial'),
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asig_labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asig', models.DateField(default=datetime.datetime.now)),
                ('desde', models.DateField(default=datetime.datetime.now)),
                ('hasta', models.DateField(default=datetime.datetime.now)),
                ('total_dias', models.IntegerField(default=0)),
                ('estado', models.IntegerField(choices=[(0, 'PENDIENTE'), (1, 'PAGADO')], default=0)),
                ('valor_a_pag', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('valor_pag', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.Labor')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='periodo.Periodo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajador.Trabajador')),
            ],
            options={
                'db_table': 'asig_labor',
                'verbose_name_plural': 'asig_labor',
                'verbose_name': 'asig_labor',
            },
        ),
    ]
