# Generated by Django 2.2.15 on 2020-08-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_labor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asig_labor',
            name='estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asig_labor',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='asig_labor',
            name='total_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asig_labor',
            name='valor_a_pag',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='asig_labor',
            name='valor_pag',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
