# Generated by Django 2.2.15 on 2020-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignar_labor', '0002_auto_20200826_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asig_labor',
            name='estado',
            field=models.IntegerField(choices=[(0, 'PENDIENTE'), (1, 'PAGADO')], default=0),
        ),
    ]
