# Generated by Django 2.2.15 on 2020-08-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['id', 'nombre'], 'verbose_name': 'insumo', 'verbose_name_plural': 'insumos'},
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria'),
        ),
    ]
