# Generated by Django 2.2.15 on 2020-08-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categoria.Categoria'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='presentacion.Presentacion'),
        ),
    ]
