# Generated by Django 2.2.15 on 2020-08-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_auto_20200814_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
