# Generated by Django 2.2.15 on 2020-08-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ACTIVO'), (0, 'INACTIVO')], default=0, unique=True),
        ),
    ]
