# Generated by Django 2.2.15 on 2020-08-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantero',
            name='estado',
            field=models.IntegerField(choices=[(0, 'ACTIVO'), (1, 'INACTIVO')], default=1),
        ),
    ]
