# Generated by Django 2.2.15 on 2020-08-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_cantero_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('decripcion', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
                'verbose_name': 'producto',
            },
        ),
    ]
