# Generated by Django 2.2.15 on 2020-08-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
