# Generated by Django 2.2.15 on 2020-08-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20200817_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pvp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
