# Generated by Django 2.2.15 on 2020-08-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_producto_pvp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-id'], 'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
